### ISSUE TITLE
Unicode characters for rho and xicor

### ISSUE THREAD

**Issue by ericmelse** [Arzik1987/medium#1]
Dear Vadim,

With great interest I am reading your [towardsdatascience.com blog post](https://towardsdatascience.com/an-undeservedly-forgotten-correlation-coefficient-86245ccb774c) about xicor and _An Undeservedly Forgotten Correlation Coefficient_
Also my thanks for the replication R code that you kindly have provided here.
One small note about that from me. In your code you have put ?? as the 'title' for rho and xicor, although for the illustrations of your blog their Greek character symbols are used.
After some browsing 'how to get' such characters in R plots, that can be done using [unicode](https://en.wikipedia.org/wiki/Greek_script_in_Unicode), like, for example in the Scalability figure code:
```
# Create plots
p1 <- plot_data(resc, "\u03C1")
p2 <- plot_data(resm, "R")
p3 <- plot_data(resx, "\u03BE")
```
I have attached my edited version of your R file.
[Vadim Arzamasov mic.R -  edited.R.txt](https://github.com/Arzik1987/medium/files/15223787/Vadim.Arzamasov.mic.R.-.edited.R.txt)

**Comment by Arzik1987** [comment]
Dear Eric,

Thank you for your feedback and suggestions! I have updated the file accordingly and made some additional rearrangements to improve readability.
